### PR TITLE
Update to SS Version 4

### PR DESCRIPTION
**Pull request by aidanator7000**
The field counter add on is now compatible and working on the master branch of Silverstripe(v4)

Namespaces were added to the FieldCounterCMSExtension.php and a _config.php file was added, as previously this addon would not working at all on SS version 3.5.1 or master

Also, a minor change in README.md was made.  It should all work in SS master now :)

### CODE REVIEW

**Comment by mylesthedev** [comment]
Hey @aidanator7000 i'll test to confirm and then merge :)

**Comment by aidanator7000** [comment]
This is my first time doing this... (the git commands still somewhat confuse me)..

looks like there may be a mistake in the way the _config.yml file uploaded...

In any case, it should read
```
SilverStripe\Admin\LeftAndMain:
  extensions:
    - FieldCounter\FieldCounterCMSExtension

```

**Comment by mylesthedev** [comment]
Did you want to commit to your repo with that fix and then it should just automatically appear above as another commit 👍

**Comment by aidanator7000** [comment]
That looks a little healthier... think it is good to go, after it is checked, ofc :) :+1:

**Comment by mylesthedev** [comment]
Legend thanks for this.

**Pull request merged**
